name: Build and run immudb-node

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Run overview showcase
        run: |
          docker run -d --rm --health-cmd "immuadmin status" --health-interval 10s --health-timeout 5s --health-retries 5 -p 3322:3322 --name immudb codenotary/immudb:1.4.1
          npx ts-node --esm ./immudb-node-showcase/src/overview-showcase.ts
          docker stop immudb
      - name: Run sql showcase
        run: |
          docker run -d --rm --health-cmd "immuadmin status" --health-interval 10s --health-timeout 5s --health-retries 5 -p 3322:3322 --name immudb codenotary/immudb:1.4.1
          npx ts-node --esm ./immudb-node-showcase/src/sql-showcase.ts
          docker stop immudb
      - name: Run zSet showcase
        run: |
          docker run -d --rm --health-cmd "immuadmin status" --health-interval 10s --health-timeout 5s --health-retries 5 -p 3322:3322 --name immudb codenotary/immudb:1.4.1
          npx ts-node --esm ./immudb-node-showcase/src/zSet-showcase.ts
          docker stop immudb
